#pragma once

// Dinh nghia cac gia tri
#define FILE_MENU_NEW 1
#define FILE_MENU_PAINT 2
#define FILE_MENU_EXIT 3
#define FILE_MENU_HELP 4
#define CHOOSE_PAINT_TRON 5
#define CHOOSE_PAINT_ELLIPSE 6
#define CHOOSE_PAINT_BANNGUYET 7
#define CHOOSE_PAINT_DAGIAC 8
#define CHOOSE_PAINT_CN 9
#define CHOOSE_PAINT_VUONG 10
#define CHOOSE_PAINT_TG 11
#define CHOOSE_PAINT_DT 12
#define INPUT_PAINT_TRON 13
#define INPUT_PAINT_ELLIPSE 14
#define INPUT_PAINT_BANNGUYET 15
#define INPUT_PAINT_DAGIAC 16
#define INPUT_PAINT_CN 17
#define INPUT_PAINT_VUONG 18
#define INPUT_PAINT_TG 19
#define INPUT_PAINT_DT 20
#define BUTTON_END 21
#define BUTTON_CHECK 22


#define MAX_LOADSTRING 100